-- Generated (by hand, following the exact tools/importer.html transform rules) from hsk4_reading_set1.json
-- Set: hsk4-r-001 (HSK4 reading) — 40 soal
-- Aman dijalankan ulang: DELETE di bawah scoped ke set_id ini saja, tidak menyentuh set lain.

BEGIN;

INSERT INTO test_sets (set_id, hsk_level, section, title, time_limit_seconds, total_questions, is_published)
VALUES ('hsk4-r-001', 4, 'reading', 'HSK 4 — Membaca (阅读) — HSK4-R-001', 2400, 40, true)
ON CONFLICT (set_id) DO UPDATE SET
  hsk_level = EXCLUDED.hsk_level,
  section = EXCLUDED.section,
  title = EXCLUDED.title,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  total_questions = EXCLUDED.total_questions,
  is_published = EXCLUDED.is_published;

DELETE FROM question_bank WHERE set_id = 'hsk4-r-001';

INSERT INTO question_bank (set_id, hsk_level, section, question_type, order_index, payload, answer, explanation, points)
VALUES
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 1, '{"instruction":"选词填空","stem":"医生说，只要每天（　）锻炼，身体就会越来越好。","stem_id":"Dokter bilang, asal tiap hari ( ) olahraga, badan akan makin sehat.","choices":[{"key":"A","hanzi":"严格","pinyin":"yángé"},{"key":"B","hanzi":"温度","pinyin":"wēndù"},{"key":"C","hanzi":"详细","pinyin":"xiángxì"},{"key":"D","hanzi":"推迟","pinyin":"tuīchí"},{"key":"E","hanzi":"坚持","pinyin":"jiānchí"},{"key":"F","hanzi":"打扰","pinyin":"dǎrǎo"}]}'::jsonb, '{"correct":"E"}'::jsonb, '答案 E：坚持（jiānchí，bertahan/konsisten）。Dokter bilang, asal tiap hari ( ) olahraga, badan akan makin sehat.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 2, '{"instruction":"选词填空","stem":"今天的（　）比昨天低多了，出门记得多穿件衣服。","stem_id":"( ) hari ini jauh lebih rendah dari kemarin, kalau keluar inget pakai baju lebih tebal.","choices":[{"key":"A","hanzi":"严格","pinyin":"yángé"},{"key":"B","hanzi":"温度","pinyin":"wēndù"},{"key":"C","hanzi":"详细","pinyin":"xiángxì"},{"key":"D","hanzi":"推迟","pinyin":"tuīchí"},{"key":"E","hanzi":"坚持","pinyin":"jiānchí"},{"key":"F","hanzi":"打扰","pinyin":"dǎrǎo"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：温度（wēndù，suhu）。( ) hari ini jauh lebih rendah dari kemarin, kalau keluar inget pakai baju lebih tebal.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 3, '{"instruction":"选词填空","stem":"这位老师对学生要求非常（　），作业错一个字都要重写。","stem_id":"Guru ini sangat ( ) ke murid, PR salah satu huruf pun harus tulis ulang.","choices":[{"key":"A","hanzi":"严格","pinyin":"yángé"},{"key":"B","hanzi":"温度","pinyin":"wēndù"},{"key":"C","hanzi":"详细","pinyin":"xiángxì"},{"key":"D","hanzi":"推迟","pinyin":"tuīchí"},{"key":"E","hanzi":"坚持","pinyin":"jiānchí"},{"key":"F","hanzi":"打扰","pinyin":"dǎrǎo"}]}'::jsonb, '{"correct":"A"}'::jsonb, '答案 A：严格（yángé，ketat/tegas）。Guru ini sangat ( ) ke murid, PR salah satu huruf pun harus tulis ulang.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 4, '{"instruction":"选词填空","stem":"会议因为经理临时有事，只好（　）到下午三点。","stem_id":"Rapat terpaksa ( ) ke jam 3 sore karena manajer ada urusan mendadak.","choices":[{"key":"A","hanzi":"严格","pinyin":"yángé"},{"key":"B","hanzi":"温度","pinyin":"wēndù"},{"key":"C","hanzi":"详细","pinyin":"xiángxì"},{"key":"D","hanzi":"推迟","pinyin":"tuīchí"},{"key":"E","hanzi":"坚持","pinyin":"jiānchí"},{"key":"F","hanzi":"打扰","pinyin":"dǎrǎo"}]}'::jsonb, '{"correct":"D"}'::jsonb, '答案 D：推迟（tuīchí，menunda）。Rapat terpaksa ( ) ke jam 3 sore karena manajer ada urusan mendadak.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 5, '{"instruction":"选词填空","stem":"关于这个计划，请你写一份更（　）的报告给我。","stem_id":"Soal rencana ini, tolong buatkan laporan yang lebih ( ) untuk saya.","choices":[{"key":"A","hanzi":"严格","pinyin":"yángé"},{"key":"B","hanzi":"温度","pinyin":"wēndù"},{"key":"C","hanzi":"详细","pinyin":"xiángxì"},{"key":"D","hanzi":"推迟","pinyin":"tuīchí"},{"key":"E","hanzi":"坚持","pinyin":"jiānchí"},{"key":"F","hanzi":"打扰","pinyin":"dǎrǎo"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：详细（xiángxì，rinci/detail）。Soal rencana ini, tolong buatkan laporan yang lebih ( ) untuk saya.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 6, '{"instruction":"选词填空","stem":"A：明天的火车是早上七点的。\nB：谢谢你（　），不然我肯定睡过头。","stem_id":"A: Kereta besok jam 7 pagi. B: Makasih udah ( ), kalau nggak pasti aku kesiangan.","choices":[{"key":"A","hanzi":"提醒","pinyin":"tíxǐng"},{"key":"B","hanzi":"后悔","pinyin":"hòuhuǐ"},{"key":"C","hanzi":"直接","pinyin":"zhíjiē"},{"key":"D","hanzi":"重点","pinyin":"zhòngdiǎn"},{"key":"E","hanzi":"修改","pinyin":"xiūgǎi"},{"key":"F","hanzi":"意见","pinyin":"yìjiàn"}]}'::jsonb, '{"correct":"A"}'::jsonb, '答案 A：提醒（tíxǐng，mengingatkan）。A: Kereta besok jam 7 pagi. B: Makasih udah ( ), kalau nggak pasti aku kesiangan.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 7, '{"instruction":"选词填空","stem":"A：你的文章写得不错，就是结尾需要再（　）一下。\nB：好的，我今天就改。","stem_id":"A: Artikelmu bagus, cuma bagian akhir perlu di( ) sedikit. B: Oke, hari ini aku ubah.","choices":[{"key":"A","hanzi":"提醒","pinyin":"tíxǐng"},{"key":"B","hanzi":"后悔","pinyin":"hòuhuǐ"},{"key":"C","hanzi":"直接","pinyin":"zhíjiē"},{"key":"D","hanzi":"重点","pinyin":"zhòngdiǎn"},{"key":"E","hanzi":"修改","pinyin":"xiūgǎi"},{"key":"F","hanzi":"意见","pinyin":"yìjiàn"}]}'::jsonb, '{"correct":"E"}'::jsonb, '答案 E：修改（xiūgǎi，merevisi）。A: Artikelmu bagus, cuma bagian akhir perlu di( ) sedikit. B: Oke, hari ini aku ubah.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 8, '{"instruction":"选词填空","stem":"A：这次没去成，你会不会（　）？\nB：不会，机会以后还有。","stem_id":"A: Kali ini gagal ikut, kamu ( ) nggak? B: Nggak, kesempatan masih ada nanti.","choices":[{"key":"A","hanzi":"提醒","pinyin":"tíxǐng"},{"key":"B","hanzi":"后悔","pinyin":"hòuhuǐ"},{"key":"C","hanzi":"直接","pinyin":"zhíjiē"},{"key":"D","hanzi":"重点","pinyin":"zhòngdiǎn"},{"key":"E","hanzi":"修改","pinyin":"xiūgǎi"},{"key":"F","hanzi":"意见","pinyin":"yìjiàn"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：后悔（hòuhuǐ，menyesal）。A: Kali ini gagal ikut, kamu ( ) nggak? B: Nggak, kesempatan masih ada nanti.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 9, '{"instruction":"选词填空","stem":"A：报告太长了，能不能说说（　）就行？\nB：好，我简单说三点。","stem_id":"A: Laporannya kepanjangan, bisa nggak sebutin ( )-nya aja? B: Oke, aku sebutin 3 poin.","choices":[{"key":"A","hanzi":"提醒","pinyin":"tíxǐng"},{"key":"B","hanzi":"后悔","pinyin":"hòuhuǐ"},{"key":"C","hanzi":"直接","pinyin":"zhíjiē"},{"key":"D","hanzi":"重点","pinyin":"zhòngdiǎn"},{"key":"E","hanzi":"修改","pinyin":"xiūgǎi"},{"key":"F","hanzi":"意见","pinyin":"yìjiàn"}]}'::jsonb, '{"correct":"D"}'::jsonb, '答案 D：重点（zhòngdiǎn，poin penting）。A: Laporannya kepanjangan, bisa nggak sebutin ( )-nya aja? B: Oke, aku sebutin 3 poin.', 1),
  ('hsk4-r-001', 4, 'reading', 'fill_blank', 10, '{"instruction":"选词填空","stem":"A：你有话就（　）说吧，不用客气。\nB：那我就说了啊。","stem_id":"A: Kalau ada yang mau diomongin ( ) aja, nggak usah sungkan. B: Ya udah aku omongin ya.","choices":[{"key":"A","hanzi":"提醒","pinyin":"tíxǐng"},{"key":"B","hanzi":"后悔","pinyin":"hòuhuǐ"},{"key":"C","hanzi":"直接","pinyin":"zhíjiē"},{"key":"D","hanzi":"重点","pinyin":"zhòngdiǎn"},{"key":"E","hanzi":"修改","pinyin":"xiūgǎi"},{"key":"F","hanzi":"意见","pinyin":"yìjiàn"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：直接（zhíjiē，langsung）。A: Kalau ada yang mau diomongin ( ) aja, nggak usah sungkan. B: Ya udah aku omongin ya.', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 11, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"可是他一点也不骄傲","id":"tapi dia sama sekali nggak sombong"},{"key":"B","hanzi":"他是我们班成绩最好的学生","id":"dia murid dengan nilai terbaik di kelas"},{"key":"C","hanzi":"还经常帮助别的同学","id":"malah sering bantu teman lain"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. dia murid dengan nilai terbaik di kelas, tapi dia sama sekali nggak sombong, malah sering bantu teman lain', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 12, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"于是我决定坐地铁去","id":"jadi aku putuskan naik kereta bawah tanah"},{"key":"B","hanzi":"今天早上路上特别堵","id":"pagi ini jalanan macet banget"},{"key":"C","hanzi":"果然比平时早到了半小时","id":"ternyata sampai setengah jam lebih awal dari biasanya"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. pagi ini jalanan macet banget, jadi aku putuskan naik kereta bawah tanah, ternyata sampai setengah jam lebih awal dari biasanya', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 13, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"首先要选好合适的地点","id":"pertama harus pilih lokasi yang pas"},{"key":"B","hanzi":"开一家饭馆并不容易","id":"buka restoran itu nggak gampang"},{"key":"C","hanzi":"然后还得考虑菜的味道和价格","id":"lalu masih harus pikirkan rasa dan harga makanan"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. buka restoran itu nggak gampang, pertama harus pilih lokasi yang pas, lalu masih harus pikirkan rasa dan harga makanan', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 14, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"这本书我看了三遍","id":"buku ini sudah kubaca tiga kali"},{"key":"B","hanzi":"每次都有新的收获","id":"tiap kali selalu ada pelajaran baru"},{"key":"C","hanzi":"所以我特别推荐给你","id":"makanya aku sangat merekomendasikannya ke kamu"}]}'::jsonb, '{"order":["A","B","C"]}'::jsonb, 'Urutan benar: ABC. buku ini sudah kubaca tiga kali, tiap kali selalu ada pelajaran baru, makanya aku sangat merekomendasikannya ke kamu', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 15, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"但是坚持了一个月以后","id":"tapi setelah bertahan satu bulan"},{"key":"B","hanzi":"刚开始跑步的时候我很累","id":"waktu awal lari aku capek banget"},{"key":"C","hanzi":"我发现自己的身体好多了","id":"aku sadar badanku jauh lebih sehat"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. waktu awal lari aku capek banget, tapi setelah bertahan satu bulan, aku sadar badanku jauh lebih sehat', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 16, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"因为外面下起了大雨","id":"karena di luar hujan deras"},{"key":"B","hanzi":"我们原来打算去公园","id":"kami awalnya mau ke taman"},{"key":"C","hanzi":"只好改在家里看电影","id":"terpaksa ganti nonton film di rumah"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. kami awalnya mau ke taman, karena di luar hujan deras, terpaksa ganti nonton film di rumah', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 17, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"它不仅方便了我们的生活","id":"ia bukan cuma memudahkan hidup kita"},{"key":"B","hanzi":"手机现在越来越重要","id":"HP sekarang makin penting"},{"key":"C","hanzi":"也改变了人们交流的方式","id":"tapi juga mengubah cara orang berkomunikasi"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. HP sekarang makin penting, ia bukan cuma memudahkan hidup kita, tapi juga mengubah cara orang berkomunikasi', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 18, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"老师让我们分成几个小组","id":"guru menyuruh kami bagi jadi beberapa kelompok"},{"key":"B","hanzi":"这样大家都能说出自己的想法","id":"dengan begini semua bisa menyampaikan pendapatnya"},{"key":"C","hanzi":"讨论今天学的内容","id":"mendiskusikan materi yang dipelajari hari ini"}]}'::jsonb, '{"order":["A","C","B"]}'::jsonb, 'Urutan benar: ACB. guru menyuruh kami bagi jadi beberapa kelompok, mendiskusikan materi yang dipelajari hari ini, dengan begini semua bisa menyampaikan pendapatnya', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 19, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"记得带上雨伞","id":"inget bawa payung"},{"key":"B","hanzi":"天气预报说明天有雨","id":"ramalan cuaca bilang besok hujan"},{"key":"C","hanzi":"免得被雨淋湿","id":"biar nggak kehujanan"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. ramalan cuaca bilang besok hujan, inget bawa payung, biar nggak kehujanan', 1),
  ('hsk4-r-001', 4, 'reading', 'ordering', 20, '{"instruction":"排列顺序","segments":[{"key":"A","hanzi":"虽然价格比别的贵一些","id":"walaupun harganya agak lebih mahal dari yang lain"},{"key":"B","hanzi":"这家店的水果很新鲜","id":"buah di toko ini segar sekali"},{"key":"C","hanzi":"但是我还是愿意来买","id":"tapi aku tetap mau beli di sini"}]}'::jsonb, '{"order":["B","A","C"]}'::jsonb, 'Urutan benar: BAC. buah di toko ini segar sekali, walaupun harganya agak lebih mahal dari yang lain, tapi aku tetap mau beli di sini', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 21, '{"instruction":"阅读理解","passage":"很多人喜欢在睡觉前玩手机，其实这个习惯对身体不好。手机的光会影响睡眠，让人更难入睡。专家建议，睡觉前一个小时最好别看手机。","passage_id":"Banyak orang suka main HP sebelum tidur, padahal kebiasaan ini nggak baik buat tubuh. Cahaya HP mengganggu tidur, bikin lebih susah terlelap. Pakar menyarankan, sejam sebelum tidur sebaiknya jangan lihat HP.","question":"睡前玩手机有什么影响？","question_id":"Apa dampak main HP sebelum tidur?","choices":[{"key":"A","hanzi":"对眼睛好","id":"baik untuk mata"},{"key":"B","hanzi":"更难入睡","id":"lebih susah tidur"},{"key":"C","hanzi":"让人开心","id":"bikin senang"},{"key":"D","hanzi":"提高效率","id":"menaikkan efisiensi"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：更难入睡（lebih susah tidur）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 22, '{"instruction":"阅读理解","passage":"我家附近新开了一家图书馆，里面又大又安静。周末的时候，我常常带孩子去那儿看书。孩子很喜欢，每次都不想回家。","passage_id":"Di dekat rumahku baru buka perpustakaan, di dalamnya luas dan tenang. Kalau akhir pekan, aku sering ajak anak baca di sana. Anaknya suka banget, tiap kali nggak mau pulang.","question":"关于那家图书馆，可以知道什么？","question_id":"Apa yang bisa diketahui tentang perpustakaan itu?","choices":[{"key":"A","hanzi":"离得很远","id":"jauh"},{"key":"B","hanzi":"环境很吵","id":"berisik"},{"key":"C","hanzi":"很受孩子欢迎","id":"disukai anak"},{"key":"D","hanzi":"只有周末开门","id":"buka cuma akhir pekan"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：很受孩子欢迎（disukai anak）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 23, '{"instruction":"阅读理解","passage":"做菜的时候，盐不能放得太早。太早放盐，菜里的水分会流出来，味道反而不好。最好等菜快熟的时候再放。","passage_id":"Saat masak, garam jangan ditaruh terlalu awal. Kalau terlalu awal, air dalam sayur keluar, rasanya malah nggak enak. Sebaiknya tunggu sampai masakan hampir matang baru ditaruh.","question":"这段话主要谈什么？","question_id":"Paragraf ini terutama membahas apa?","choices":[{"key":"A","hanzi":"怎么买菜","id":"cara beli sayur"},{"key":"B","hanzi":"放盐的时间","id":"waktu menaruh garam"},{"key":"C","hanzi":"菜的价格","id":"harga sayur"},{"key":"D","hanzi":"做菜的工具","id":"alat masak"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：放盐的时间（waktu menaruh garam）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 24, '{"instruction":"阅读理解","passage":"小王刚来公司的时候，什么都不会，经常出错。但他很努力，遇到不懂的就问同事。半年以后，他已经成了部门里最能干的人之一。","passage_id":"Waktu Xiao Wang baru masuk perusahaan, dia nggak bisa apa-apa, sering salah. Tapi dia rajin, kalau nggak ngerti langsung tanya rekan. Setengah tahun kemudian, dia sudah jadi salah satu yang paling cakap di divisinya.","question":"小王现在怎么样？","question_id":"Xiao Wang sekarang bagaimana?","choices":[{"key":"A","hanzi":"还是常出错","id":"masih sering salah"},{"key":"B","hanzi":"离开了公司","id":"keluar dari perusahaan"},{"key":"C","hanzi":"工作能力强","id":"kemampuan kerjanya kuat"},{"key":"D","hanzi":"不爱问问题","id":"nggak suka bertanya"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：工作能力强（kemampuan kerjanya kuat）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 25, '{"instruction":"阅读理解","passage":"旅行不一定要去很远的地方。有时候，就在自己生活的城市里走一走，也能发现很多以前没注意到的美丽风景。","passage_id":"Traveling nggak harus ke tempat jauh. Kadang, cukup jalan-jalan di kota tempat kita tinggal, kita bisa menemukan banyak pemandangan indah yang dulu nggak kita perhatikan.","question":"这段话告诉我们：","question_id":"Paragraf ini memberitahu kita:","choices":[{"key":"A","hanzi":"旅行很花钱","id":"traveling boros"},{"key":"B","hanzi":"近处也有美景","id":"dekat pun ada pemandangan indah"},{"key":"C","hanzi":"远方更好玩","id":"tempat jauh lebih seru"},{"key":"D","hanzi":"别一个人旅行","id":"jangan traveling sendirian"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：近处也有美景（dekat pun ada pemandangan indah）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 26, '{"instruction":"阅读理解","passage":"很多年轻人找工作时只看工资，其实这样不太好。除了工资，还应该考虑这份工作能不能让自己学到东西，有没有发展的机会。","passage_id":"Banyak anak muda cari kerja cuma lihat gaji, padahal itu kurang bagus. Selain gaji, harus juga dipikir apakah kerjaan ini bisa bikin kita belajar sesuatu, ada peluang berkembang atau nggak.","question":"找工作时，作者认为应该：","question_id":"Saat cari kerja, menurut penulis sebaiknya:","choices":[{"key":"A","hanzi":"只看工资","id":"cuma lihat gaji"},{"key":"B","hanzi":"选离家近的","id":"pilih yang dekat rumah"},{"key":"C","hanzi":"考虑发展机会","id":"pertimbangkan peluang berkembang"},{"key":"D","hanzi":"听父母的意见","id":"ikuti pendapat ortu"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：考虑发展机会（pertimbangkan peluang berkembang）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 27, '{"instruction":"阅读理解","passage":"养成读书的习惯很重要。每天哪怕只读十分钟，时间长了，你读过的书也会变成一笔很大的财富，让你变得更聪明。","passage_id":"Membangun kebiasaan membaca itu penting. Tiap hari meski cuma 10 menit, lama-lama buku yang sudah kamu baca akan jadi kekayaan besar, bikin kamu lebih pintar.","question":"根据这段话，读书：","question_id":"Menurut paragraf ini, membaca:","choices":[{"key":"A","hanzi":"浪费时间","id":"buang waktu"},{"key":"B","hanzi":"要读得很快","id":"harus cepat"},{"key":"C","hanzi":"每天读很久","id":"tiap hari harus lama"},{"key":"D","hanzi":"贵在坚持","id":"yang penting konsisten"}]}'::jsonb, '{"correct":"D"}'::jsonb, '答案 D：贵在坚持（yang penting konsisten）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 28, '{"instruction":"阅读理解","passage":"笑对身体有很多好处。经常笑的人不容易生病，看起来也更年轻。所以，遇到不开心的事，试着笑一笑，也许问题就没那么难了。","passage_id":"Tertawa punya banyak manfaat buat tubuh. Orang yang sering tertawa nggak gampang sakit, kelihatan lebih muda juga. Jadi, kalau ada hal yang nggak menyenangkan, coba tersenyum, mungkin masalahnya jadi nggak seberat itu.","question":"这段话主要想告诉我们：","question_id":"Paragraf ini terutama ingin memberitahu:","choices":[{"key":"A","hanzi":"别乱开玩笑","id":"jangan sembarangan bercanda"},{"key":"B","hanzi":"笑对身体好","id":"tertawa baik untuk tubuh"},{"key":"C","hanzi":"年轻人爱笑","id":"anak muda suka tertawa"},{"key":"D","hanzi":"生病要看医生","id":"sakit harus ke dokter"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：笑对身体好（tertawa baik untuk tubuh）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 29, '{"instruction":"阅读理解","passage":"每个人都会遇到失败。失败并不可怕，可怕的是失败以后就放弃。其实，失败能让我们发现自己的问题，只要认真总结，下次就能做得更好。所以说，失败也是一种财富。","passage_id":"Setiap orang pasti mengalami kegagalan. Gagal itu nggak menakutkan, yang menakutkan adalah menyerah setelah gagal. Sebenarnya, kegagalan membuat kita menemukan masalah kita sendiri; asal serius mengevaluasi, lain kali bisa lebih baik. Jadi, kegagalan juga sebuah kekayaan.","question":"作者觉得失败以后最不应该：","question_id":"Menurut penulis, setelah gagal yang paling tidak boleh:","choices":[{"key":"A","hanzi":"总结经验","id":"mengevaluasi pengalaman"},{"key":"B","hanzi":"马上放弃","id":"langsung menyerah"},{"key":"C","hanzi":"继续努力","id":"terus berusaha"},{"key":"D","hanzi":"找出问题","id":"mencari masalah"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：马上放弃（langsung menyerah）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 30, '{"instruction":"阅读理解","passage":"每个人都会遇到失败。失败并不可怕，可怕的是失败以后就放弃。其实，失败能让我们发现自己的问题，只要认真总结，下次就能做得更好。所以说，失败也是一种财富。","passage_id":"Setiap orang pasti mengalami kegagalan. Gagal itu nggak menakutkan, yang menakutkan adalah menyerah setelah gagal. Sebenarnya, kegagalan membuat kita menemukan masalah kita sendiri; asal serius mengevaluasi, lain kali bisa lebih baik. Jadi, kegagalan juga sebuah kekayaan.","question":"这段话主要想告诉我们：","question_id":"Paragraf ini terutama ingin memberitahu:","choices":[{"key":"A","hanzi":"失败很可怕","id":"kegagalan menakutkan"},{"key":"B","hanzi":"别怕失败","id":"jangan takut gagal"},{"key":"C","hanzi":"成功很容易","id":"sukses itu gampang"},{"key":"D","hanzi":"要少犯错误","id":"harus sedikit berbuat salah"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：别怕失败（jangan takut gagal）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 31, '{"instruction":"阅读理解","passage":"现在很多人习惯用电脑打字，很少用笔写字了。时间长了，有些字虽然认识，但是拿起笔却写不出来。所以，我们平时也应该多练习写字。","passage_id":"Sekarang banyak orang terbiasa mengetik pakai komputer, jarang nulis pakai pena. Lama-lama, ada huruf yang meski kenal, tapi begitu pegang pena malah nggak bisa nulisnya. Jadi, sehari-hari kita juga perlu lebih banyak latihan menulis.","question":"为什么有些字写不出来？","question_id":"Kenapa ada huruf yang nggak bisa ditulis?","choices":[{"key":"A","hanzi":"太难了","id":"terlalu susah"},{"key":"B","hanzi":"没学过","id":"belum pernah belajar"},{"key":"C","hanzi":"很少用笔写","id":"jarang nulis pakai pena"},{"key":"D","hanzi":"电脑坏了","id":"komputer rusak"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：很少用笔写（jarang nulis pakai pena）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 32, '{"instruction":"阅读理解","passage":"这家餐厅的服务很有特点。客人还没开口，服务员就能猜到他们需要什么。正因为这样，很多客人都愿意常常来这儿吃饭。","passage_id":"Pelayanan restoran ini punya ciri khas. Sebelum tamu buka mulut, pelayannya sudah bisa menebak apa yang mereka butuh. Justru karena itu, banyak tamu mau sering makan di sini.","question":"客人为什么愿意常来？","question_id":"Kenapa tamu mau sering datang?","choices":[{"key":"A","hanzi":"菜很便宜","id":"masakan murah"},{"key":"B","hanzi":"离家很近","id":"dekat rumah"},{"key":"C","hanzi":"服务很好","id":"pelayanan bagus"},{"key":"D","hanzi":"环境安静","id":"suasana tenang"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：服务很好（pelayanan bagus）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 33, '{"instruction":"阅读理解","passage":"别人给你提意见的时候，先别急着生气。有时候，正是这些意见能帮我们看到自己看不到的缺点，让我们进步得更快。","passage_id":"Waktu orang memberi masukan, jangan buru-buru marah. Kadang, justru masukan itulah yang membantu kita melihat kekurangan yang nggak kita lihat sendiri, bikin kita maju lebih cepat.","question":"应该怎样对待别人的意见？","question_id":"Bagaimana seharusnya menyikapi masukan orang lain?","choices":[{"key":"A","hanzi":"马上生气","id":"langsung marah"},{"key":"B","hanzi":"完全不听","id":"sama sekali nggak dengar"},{"key":"C","hanzi":"认真接受","id":"menerima dengan serius"},{"key":"D","hanzi":"直接拒绝","id":"langsung menolak"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：认真接受（menerima dengan serius）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 34, '{"instruction":"阅读理解","passage":"小张大学学的是音乐，毕业后却当了一名记者。有人觉得可惜，但他说，虽然工作和专业不一样，可是大学学到的东西让他做事更认真、更有耐心，这些对他现在的工作帮助很大。","passage_id":"Xiao Zhang kuliah jurusan musik, tapi setelah lulus malah jadi wartawan. Ada yang merasa sayang, tapi dia bilang, meski kerjaan dan jurusannya beda, hal-hal yang dia pelajari di kuliah membuatnya lebih teliti dan sabar, dan itu sangat membantu pekerjaannya sekarang.","question":"小张现在做什么工作？","question_id":"Xiao Zhang sekarang kerja apa?","choices":[{"key":"A","hanzi":"音乐老师","id":"guru musik"},{"key":"B","hanzi":"记者","id":"wartawan"},{"key":"C","hanzi":"歌手","id":"penyanyi"},{"key":"D","hanzi":"医生","id":"dokter"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：记者（wartawan）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 35, '{"instruction":"阅读理解","passage":"小张大学学的是音乐，毕业后却当了一名记者。有人觉得可惜，但他说，虽然工作和专业不一样，可是大学学到的东西让他做事更认真、更有耐心，这些对他现在的工作帮助很大。","passage_id":"Xiao Zhang kuliah jurusan musik, tapi setelah lulus malah jadi wartawan. Ada yang merasa sayang, tapi dia bilang, meski kerjaan dan jurusannya beda, hal-hal yang dia pelajari di kuliah membuatnya lebih teliti dan sabar, dan itu sangat membantu pekerjaannya sekarang.","question":"小张觉得大学的学习：","question_id":"Menurut Xiao Zhang, kuliahnya:","choices":[{"key":"A","hanzi":"没有用","id":"nggak berguna"},{"key":"B","hanzi":"很浪费时间","id":"buang waktu"},{"key":"C","hanzi":"对现在有帮助","id":"membantu sekarang"},{"key":"D","hanzi":"应该换专业","id":"harusnya ganti jurusan"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：对现在有帮助（membantu sekarang）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 36, '{"instruction":"阅读理解","passage":"天气越来越热了，很多人喜欢喝冰的东西。但是医生提醒，一次喝太多冰水对胃不好，特别是运动以后，最好先休息一会儿再喝。","passage_id":"Cuaca makin panas, banyak orang suka minum yang dingin. Tapi dokter mengingatkan, sekali minum es terlalu banyak nggak baik buat lambung, apalagi setelah olahraga, sebaiknya istirahat dulu sebentar baru minum.","question":"医生提醒我们什么？","question_id":"Dokter mengingatkan kita apa?","choices":[{"key":"A","hanzi":"别喝水","id":"jangan minum air"},{"key":"B","hanzi":"多运动","id":"banyak olahraga"},{"key":"C","hanzi":"别一次喝太多冰水","id":"jangan sekali minum banyak air es"},{"key":"D","hanzi":"运动后马上喝水","id":"langsung minum setelah olahraga"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：别一次喝太多冰水（jangan sekali minum banyak air es）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 37, '{"instruction":"阅读理解","passage":"父母的一言一行都会影响孩子。如果父母自己天天看手机，却让孩子去读书，孩子往往是不会听的。想教育好孩子，父母首先要做好自己。","passage_id":"Setiap ucapan dan tindakan orang tua memengaruhi anak. Kalau orang tua sendiri tiap hari main HP, tapi menyuruh anak baca buku, anak biasanya nggak akan nurut. Kalau mau mendidik anak dengan baik, orang tua harus lebih dulu memperbaiki diri.","question":"这段话主要谈：","question_id":"Paragraf ini terutama membahas:","choices":[{"key":"A","hanzi":"手机的坏处","id":"bahaya HP"},{"key":"B","hanzi":"孩子爱读书","id":"anak suka membaca"},{"key":"C","hanzi":"父母的影响","id":"pengaruh orang tua"},{"key":"D","hanzi":"怎么买手机","id":"cara beli HP"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：父母的影响（pengaruh orang tua）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 38, '{"instruction":"阅读理解","passage":"很多事情，看起来很难，其实只要开始去做，就会发现没有想象中那么难。最难的往往不是事情本身，而是开始的那一步。","passage_id":"Banyak hal kelihatannya susah, padahal asal mulai dikerjakan, kita akan sadar nggak sesusah yang dibayangkan. Yang paling sulit sering bukan hal itu sendiri, melainkan langkah pertama untuk memulai.","question":"作者认为最难的是：","question_id":"Menurut penulis, yang paling sulit adalah:","choices":[{"key":"A","hanzi":"事情本身","id":"hal itu sendiri"},{"key":"B","hanzi":"开始去做","id":"mulai mengerjakan"},{"key":"C","hanzi":"坚持下去","id":"bertahan"},{"key":"D","hanzi":"找到方法","id":"menemukan cara"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：开始去做（mulai mengerjakan）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 39, '{"instruction":"阅读理解","passage":"有一位老人在海边散步，看到很多小鱼被海水冲到了沙滩上。他一条一条地把鱼扔回海里。有人问他：“这么多鱼，你救得过来吗？谁会在乎呢？”老人一边扔一边说：“这条鱼在乎，这条也在乎。”","passage_id":"Seorang kakek berjalan-jalan di pantai, melihat banyak ikan kecil terhempas ombak ke atas pasir. Ia melempar ikan-ikan itu kembali ke laut satu per satu. Ada yang bertanya: ''Ikan sebanyak ini, memang kamu bisa selamatkan semua? Siapa yang peduli?'' Sambil melempar, kakek itu menjawab: ''Ikan ini peduli, yang ini juga peduli.''","question":"老人在做什么？","question_id":"Kakek itu sedang apa?","choices":[{"key":"A","hanzi":"钓鱼","id":"memancing"},{"key":"B","hanzi":"游泳","id":"berenang"},{"key":"C","hanzi":"把鱼扔回海里","id":"melempar ikan kembali ke laut"},{"key":"D","hanzi":"在沙滩上睡觉","id":"tidur di pantai"}]}'::jsonb, '{"correct":"C"}'::jsonb, '答案 C：把鱼扔回海里（melempar ikan kembali ke laut）', 1),
  ('hsk4-r-001', 4, 'reading', 'reading_mc', 40, '{"instruction":"阅读理解","passage":"有一位老人在海边散步，看到很多小鱼被海水冲到了沙滩上。他一条一条地把鱼扔回海里。有人问他：“这么多鱼，你救得过来吗？谁会在乎呢？”老人一边扔一边说：“这条鱼在乎，这条也在乎。”","passage_id":"Seorang kakek berjalan-jalan di pantai, melihat banyak ikan kecil terhempas ombak ke atas pasir. Ia melempar ikan-ikan itu kembali ke laut satu per satu. Ada yang bertanya: ''Ikan sebanyak ini, memang kamu bisa selamatkan semua? Siapa yang peduli?'' Sambil melempar, kakek itu menjawab: ''Ikan ini peduli, yang ini juga peduli.''","question":"这个故事主要想告诉我们：","question_id":"Cerita ini terutama ingin memberitahu:","choices":[{"key":"A","hanzi":"老人很有钱","id":"kakek itu kaya"},{"key":"B","hanzi":"每一个都值得在乎","id":"setiap satu layak dipedulikan"},{"key":"C","hanzi":"海边很危险","id":"pantai berbahaya"},{"key":"D","hanzi":"小鱼很好吃","id":"ikan kecil enak"}]}'::jsonb, '{"correct":"B"}'::jsonb, '答案 B：每一个都值得在乎（setiap satu layak dipedulikan）', 1);

COMMIT;
